name: Deploy

permissions:
  actions: read
  contents: read
  checks: read
  packages: write
  statuses: write


on:
  release:
    types: [published]
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.beta[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+.alpha[0-9]+'

jobs:
  push_to_github_packages:
    name: Push to Packfiles GitHub Packages
    runs-on: ubuntu-latest
    steps:
    - name: Set RELEASE_TAG
      run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: Check Playwright::version
      run: bundle exec ruby -e 'raise "invalid Playwright::VERSION" unless Playwright::VERSION == ENV["RELEASE_TAG"]'
    - name: Generate API codes and build
      run: |
        bundle exec ruby development/generate_api.rb
        rake build
    - name: Set GitHub Packages API Key
      run: |
        set +x
        mkdir -p ~/.gem
        cat << EOF > ~/.gem/credentials
        ---
        :github: Bearer ${{ secrets.GITHUB_TOKEN }}
        EOF

        chmod 0600 ~/.gem/credentials
        set -x

    - run: gem push pkg/playwright-ruby-client-$RELEASE_TAG.gem --key github --host "https://rubygems.pkg.github.com/packfiles"
